"use strict";
exports.__esModule = true;
var express = require("express");
var router = express.Router();
var memberRouter = require('./member/MemberRoute');
var customerRouter = require('./customer/CustomerRoute');
// const categoryRouter = require('./category/CategoryRoute');
var CategoryRoute_1 = require("./category/CategoryRoute");
var boardRouter = require('./board/BoardRoute');
var postRouter = require('./post/PostRoute');
var commentRouter = require('./comment/CommentRoute');
var visitorRouter = require('./visitor/VisitorController');
var mailRouter = require('./mail/MailRoute');
var common = require('../common/common');
router.get('/search/:keyword', function (req, res) {
    var result = common.result;
    result.code = 'DR00';
    result.message = common.status.DR00;
    var keyword = req.params.keyword;
    result.data = keyword;
    return res.json(result);
});
router.use('/member', memberRouter);
router.use('/customer', customerRouter);
router.use('/category', CategoryRoute_1["default"]);
router.use('/board', boardRouter);
router.use('/post', postRouter);
router.use('/comment', commentRouter);
router.use('/visitor', visitorRouter);
router.use('/mail', mailRouter);
exports["default"] = router;
